### ISSUE TITLE
LinUCB returning NaN in predicted rewards/ response

### ISSUE THREAD

**Issue by ayush488** [fidelity/mab2rec#17]
What could be the reason that LinUCB is returning NaN in the predicted rewards? 
LinGreedy is working fine with the same data.

**Comment by bkleyn** [comment]
If you provide a minimal example (code and data) to reproduce this error we can have a closer look.

My only guess here would be to make sure that you have enough observations for each arm/item. For LinUCB variance is undefined if you were to have only one observation for a given arm/item for example.

**Comment by ayush488** [comment]
Got..it.. so that would be the problem.. My data does not have " enough
observations for each arm/item"

Regards,
Ayush
