### ISSUE TITLE
Limiting the actions/arms to choose from during scoring

### ISSUE THREAD

**Issue by ayush488** [fidelity/mab2rec#18]
Once the bandit is trained with all the arms/actions- context- reward triplets, is it possible to constrain the recommendations/ scoring for each person to a few arms/actions?

**Comment by bkleyn** [comment]
Yes, it is possible to specify the eligible arms/actions for each user. See the [Advanced](https://github.com/fidelity/mab2rec/blob/main/notebooks/5_advanced.ipynb) notebook for an example under "Item Eligibility per User" heading.

**Comment by ayush488** [comment]
Also how to get recommendation for a new user (who is not in training data)

**Comment by ayush488** [comment]
?

**Comment by Akshaysharma29** [comment]
Hi, @ayush488 were you able to find a way to add a new user?
