### ISSUE TITLE
User Features Change Over Time How We Should Feed Data

### ISSUE THREAD

**Issue by mustfkeskin** [fidelity/mab2rec#27]
User and item properties may change over time. 
How should I prepare the dataframe while giving it to the model?
Because the userid will still be the same

**Comment by mustfkeskin** [comment]
I can change the user information that way, but the item_id corresponds to the number of arms. How can I change item features?

**Comment by mustfkeskin** [comment]
Hi serdar
Thanks for detailed answer

Let me explain a little more about the problem I'm dealing with.

I want to sort the widgets on the e-commerce site. In this context, I have user and widget features.
I want to add the performance information of the widgets while sorting them. Like click through rate(ctr) and conversion rate(cr). There are instant campaigns, and depending on that  the ctr values can change quickly.
Like the last 3 hours of ctr.

```
arm_to_features = {'Arm1': [0, 1], 'Arm2': [0, 0], 'Arm3': [0, 0], 'Arm4': [0, 1]}
'Arm1': [0, 1] --> [ctr3h, ctr24h]
```
This information may be different for morning, noon and evening.


I  want to use user features and item features together.

If I use warm start, I can initialize the arms. but I am not able to give the time dependent changes to the model. How can I give such time dependent changes to the model?

**Comment by Akshaysharma29** [comment]
@mustfkeskin how are you defining rewards?
