### ISSUE TITLE
Unable to find item_features being used

### ISSUE THREAD

**Issue by Sankalp96** [fidelity/mab2rec#28]
Can you please explain where have you used the item_features? I don't seem to find it being used anywhere except for loading.

**Comment by skadio** [comment]
Check for warm-start() function that uses item features

**Comment by Akshaysharma29** [comment]
1. Hi @skadio AFAIK warm-start is used to solve cold and not to use features for training. CMIIW.


2. @Sankalp96 were you able to identify how to use the item feature?
