### ISSUE TITLE
How can we implement contextual volatile MABs?

### ISSUE THREAD

**Issue by Sankalp96** [fidelity/mab2rec#29]
How can we implement contextual volatile MABs?

**Comment by bkleyn** [comment]
Hey @Sankalp96 

Unfortunately, Contextual Volatile MAB is not one of the policies implemented in MABWiser. Assuming the policy is consistent with the current design, you are welcome to make a contribution to the library. See this [guide](https://fidelity.github.io/mabwiser/new_bandit.html) for steps to add a new bandit.
