### ISSUE TITLE
Recommending for a single context fails

### ISSUE THREAD

**Issue by bjarlestam** [fidelity/mab2rec#36]
When calling the recommend function with a single context I get the following error (ValueError: If using all scalar values, you must pass an index). 

It works fine to get recommendations for two or more contexts. 

This notebook has a minimal example of the problem: https://colab.research.google.com/drive/1gubWTFNaQ1m6vhQ_fGlydo0_2I6WnJTI?usp=sharing

**Comment by Akshaysharma29** [comment]
Hi @bjarlestam Yes I am facing the same issue. did you find the solution or reason?

**Comment by bjarlestam** [comment]
My temporary workaround was to duplicate the input and generate two recommendations, then just take the first one. I have unfortunately not had time to dig into the code to try to debug it.

**Comment by Akshaysharma29** [comment]
got it @bjarlestam , let's for wait the official response.

**Comment by Akshaysharma29** [comment]
@bjarlestam if possible can you share what is your use case? where do you need single user prediction?

**Comment by bjarlestam** [comment]
I use it to generate recommendations for specific users in an online setting
