### ISSUE TITLE
Errors for "NoReturn" type

### ISSUE THREAD

**Issue by SaraEkmanSVT** [fidelity/mab2rec#38]
The [NoReturn type](https://docs.python.org/3/library/typing.html#typing.NoReturn) is used in these places:
- https://github.com/fidelity/mab2rec/blob/698088844cef6cb597e97c92e1189bb62148d2c5/mab2rec/rec.py#L155
- https://github.com/fidelity/mab2rec/blob/698088844cef6cb597e97c92e1189bb62148d2c5/mab2rec/utils.py#L399
- https://github.com/fidelity/mab2rec/blob/698088844cef6cb597e97c92e1189bb62148d2c5/mab2rec/pipeline.py#L36

"NoReturn" is meant to be used to end further processing, for example when calling `exit()`. The functions above returns nothing (explicitly) but are not meant to end the program, which results in editor warnings about code after this being unreachable. What you might want to use instead is the None type, i.e.: `func() -> None` instead of `func() -> NoReturn`

**Comment by skadio** [comment]
Hi @SaraEkmanSVT , thank you for pointing it out, you are absolutely correct! We have noticed this too, but never had the chance to get to it..
