### ISSUE TITLE
Ranking using MAB

### ISSUE THREAD

**Issue by Akshaysharma29** [fidelity/mab2rec#43]
Hi Team, Thanks for creating this library. Can you guide me on how to use this library for ranking?

**Comment by bkleyn** [comment]
Hey @Akshaysharma29 

Thanks for your interest in the library.

As shown in our simple usage example below, Mab2Rec allows you to specify a `top_k` argument which will determine the number of items to recommend/return for each user (in ranked order). The library is not making use of ranking loss metrics specifically, but you can evaluate the output using ranking metrics such as Mean Average Precision (MAP) and Normalized Discounted Cumulative Gains (NDCG) - which are available in our [Jurity](https://github.com/fidelity/jurity) library.

```python
# Import 
from mab2rec import BanditRecommender, LearningPolicy
from mab2rec.pipeline import train, score

# LinGreedy recommender to select top-4 items with 10% random exploration 
rec = BanditRecommender(LearningPolicy.LinGreedy(epsilon=0.1), top_k=4)

# Train on (user, item, response) interactions in train data using user features 
train(rec, data='data/data_train.csv', 
      user_features='data/features_user.csv')

# Score recommendations for users in test data. The output df holds 
# user_id, item_id, score columns for every test user for top-k items 
df = score(rec, data='data/data_test.csv', 
           user_features='data/features_user.csv')
```

**Comment by Akshaysharma29** [comment]
Thanks for the clarification @bkleyn :)
Are you guys planning to add ranking loss or guide me on how I can add ranking loss? because relative position also matters in some use-cases.

**Comment by skadio** [comment]
My guess is that you can revise your "reward" columns in the data with some form of ranking loss to take position bias into account.
