### ISSUE TITLE
Including cold-start items in the training process and recommended way of examining the cold-start problem via using mab2rec

### ISSUE THREAD

**Issue by shengyenlin** [fidelity/mab2rec#48]
Hello everyone,

Thanks for developing this amazing package!

I'm currently using this package to deal with the cold-start problem with my dataset and I found some difficulties when using this package to analyze the cold-start problem.

First, I try to include the cold items (items that exist in the training set but not in the testing dataset) before running some algorithms with random nature (epsilon greedy, Thomson Sampling, UCB1, etc.) with the following code.

```

recs = ['TS', 'EplisonGreedy']

train_item = train_df["item_id"].unique()
test_item = test_df["item_id"].unique()
cold_start_items = list(set(test_item) - set(train_item))
all_items = list(set(test_item) | set(train_item))

recommenders = {   
"TS": BanditRecommender(
        learning_policy=LearningPolicy.ThompsonSampling(),
        n_jobs=-2
        ),
    "EplisonGreedy": BanditRecommender(
        learning_policy=LearningPolicy.EpsilonGreedy(epsilon=0.4),
        n_jobs=-2
        ) 

for rec in recs:
    recommenders[rec].set_arms(all_items)

reco_to_results_all_user, reco_to_metrics_all_user = benchmark(
    recommenders,
    metrics=metrics,
    train_data=train_df, 
    test_data=test_df,
    verbose=True
    )
```

When examing the recommendation result (`reco_to_results_all_user`), I found that no cold items were recommended. However, I think there must be a small probability that these cold items were recommended, or was my way of adding cold items wrong ?

In addition, from the [5_advanced.ipynb](https://github.com/fidelity/mab2rec/blob/main/notebooks/5_advanced.ipynb) notebook, I learned that one could warm start a cold item with item features after training the algorithm. However, I was thinking if it's possible to directly integrate the cold-start items before training the algorithm. (Such that the algorithm know they are bad choices, but they were somehow chosen once or twice by the algorithm's random nature)

Thanks in advance !

**Comment by skadio** [comment]
Great question. 

_**IF** I remember correctly_, the "arms" of the bandit are created during the Training, with the arms/items seen in training data. As such, during Test time, even if there is a net-new item, there won't be a corresponding "arm" for it, hence the model cannot recommend it. 

As you rightly pointed out, you can feed in "item features". Then the `warm_start()` can start the new item with the pre-trained model of a close-enough arm. Details in advanced notebook. 

The other option is to use the `add_arm()` functionality. IF a new item arrives, which is NOT part of the existing arms, then you can call the `add_arm()` and introduce a new arm/bandit to the system. Unlike warm_start() this new arm will initialize with a not-trained model. As expected, they are going to be selected that much (depending on the exploration part of the learning policy) but yes, they will be chosen sporadically. 

Unlike an experimental/benchmark setup where we fit a Train data and then score on a Test data, the scenario you are hinting above sounds a real-sytem with a streaming of recommendations, and new items emerging and some others disappearing etc. (see also `remove_arm()` for that purpose). 

Hope this helps,
