### ISSUE TITLE
response values

### ISSUE THREAD

**Issue by ayush488** [fidelity/mab2rec#9]
in the user item interaction data.. can the response be a real number or integer and not just binary 0 or 1?

**Comment by ayush488** [comment]
But if I want to optimize my reward and not the binary version of it then how should I do....

**Comment by bkleyn** [comment]
You can train a recommender and score recommendations as shown in the Quick Start example for an Individual Recommender in the project README.md.

**Comment by ayush488** [comment]
I tried this 
"LinUCB": BanditRecommender(learning_policy=LearningPolicy.LinUCB(alpha=1.25),n_jobs=-1),
the model got trained but when I scored the test data... all scores came out nan..
can you explain why?
